#
# cmake/reflect/_Sources.cmake is generated by `mulle-sde reflect`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( SOURCES
src/MulleObjCUnicodeFoundation.m
src/NSCharacterSet+MulleObjCUnicode.m
src/NSMutableCharacterSet+MulleObjCUnicode.m
src/NSString+MulleObjCUnicode.m
)

set( STAGE2_SOURCES
src/MulleObjCLoader+MulleObjCUnicodeFoundation.m
)
