      { @selector( MulleObjCLoader), @selector( MulleObjCContainerFoundation) },      // 47a9beb6;MulleObjCLoader;2132102f;MulleObjCContainerFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCStandardFoundation) },      // 47a9beb6;MulleObjCLoader;ed704a42;MulleObjCStandardFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCTimeFoundation) },      // 47a9beb6;MulleObjCLoader;cc20d48b;MulleObjCTimeFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCValueFoundation) },      // 47a9beb6;MulleObjCLoader;535d5103;MulleObjCValueFoundation
      { @selector( NSCharacterSet), @selector( MulleObjCUnicode) },      // bb258d72;NSCharacterSet;4d57c73a;MulleObjCUnicode
      { @selector( NSMutableCharacterSet), @selector( MulleObjCUnicode) },      // a5cef654;NSMutableCharacterSet;4d57c73a;MulleObjCUnicode
      { @selector( NSString), @selector( MulleObjCUnicode) },      // 1994a171;NSString;4d57c73a;MulleObjCUnicode
