      { @selector( MulleObjCLoader), @selector( MulleObjCStandardFoundation) },      // 47a9beb6;MulleObjCLoader;ed704a42;MulleObjCStandardFoundation
      { @selector( NSCharacterSet), @selector( MulleObjCUnicode) },      // bb258d72;NSCharacterSet;4d57c73a;MulleObjCUnicode
      { @selector( NSMutableCharacterSet), @selector( MulleObjCUnicode) },      // a5cef654;NSMutableCharacterSet;4d57c73a;MulleObjCUnicode
      { @selector( NSString), @selector( MulleObjCUnicode) },      // 1994a171;NSString;4d57c73a;MulleObjCUnicode
